### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by dgarcia360**
Update with the icons shared by the marketing team.

## Tests

New icons within cards:

image

New icons in navbar:

image

### CODE REVIEW

**Comment by dgarcia360** [comment]
@annastuchlik Ready for review

**Comment by annastuchlik** [comment]
@dgarcia360 The icons in the navbar look great.

My preview doesn't show the new icons (I've cleaned the cache and used incognito mode), but I assume we don't need them here.
Are you going to use them to update this PR? https://github.com/scylladb/scylladb/pull/13559

**Comment by dgarcia360** [comment]
@annastuchlik I've not changed the icons in the homepage in this pull request. I'll include them in https://github.com/scylladb/scylladb/pull/13559 after we update to 1.5

**Comment by annastuchlik** [comment]
So I thought, but I had to make sure. Thanks.

**Review by annastuchlik — APPROVED** [review]
LGTM

**Pull request merged**
