### PR TITLE
Remove bg panel-box

### PR DESCRIPTION
**Pull request by dgarcia360**
Removes the panel box background.

**Before**

image

**Now**

image

### CODE REVIEW

**Comment by dgarcia360** [comment]
I've also tried with a border, but it does not look nice imo:

image

**Comment by tzach** [comment]
Look better without the border IMHO.
What do you think?

**Comment by dgarcia360** [comment]
I prefer the version without the border (white background).

**Comment by tzach** [comment]
LGTM (with out the border)

**Pull request merged**
