### PR TITLE
feat: add new logo & mascots

### LINKED ISSUE #1181: update scylladb logo
The ScyllaDB logo has been refreshed, attaching svg
scylladb-logo-horizontal

Also when updating please check the visual center line (horizontal) as the text DOCUMENTATION looks misaligned (may need to adjust padding of logo itself)
image

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes #1181 

image

## How to test

Build the docs and see the new logo.

To check the available mascots, open: http://127.0.0.1:5500/examples/mascots/

## Next steps

Once we release a new version of the theme, we will need to manually change the mascots in the following projects:

- https://docs.scylladb.com/stable/
- https://iot.scylladb.com/
- https://feature-store.scylladb.com/stable/
- https://cloud.docs.scylladb.com/stable/
- https://gaming-leaderboard.scylladb.com/stable/

### CODE REVIEW

**Comment by dgarcia360** [comment]
@annastuchlik @kwiato I couldn't find  the following mascots updated, please advice what to use instead:

image
image
image
image
image

**Comment by kwiato** [comment]
Added two mascots myself. Asked Julia for the other 3, I'll update them as soon as I get them.

**Comment by dgarcia360** [comment]
Thanks @kwiato! Added the two new mascots:

image

**Comment by dgarcia360** [comment]
We are missing:

- docs
- manager
- carepet

**Comment by kwiato** [comment]
@dgarcia360 Added new mascots to figma
image

**Comment by dgarcia360** [comment]
New mascots added

**Pull request merged**
