### PR TITLE
Add enlarge images button

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/187

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:

```
make preview
````

3. Open http://127.0.0.1:5500/ with your favorite browser. Then, navigate to "Examples" > "Images". At the end of the page, you will find an example on how to use the custom class "enlarge-image".

## Screenshots

image

image

### CODE REVIEW

**Comment by tzach** [comment]
When I test this localy, clicking the image send me to http://localhost:5500/_images/diagram.svg
not a pop up

**Comment by tzach** [comment]
Do we need to add directive to each image to support this?

**Comment by tzach** [comment]
```
WARNING: error while formatting arguments for sphinx_scylladb_theme.extensions.substitutions.substitution_code_role: type object 'list' has no attribute '_special'
```

**Comment by tzach** [comment]
image

**Comment by tzach** [comment]
Make this option default for all images with `width`

**Comment by tzach** [comment]
Nice example from stripe:
https://stripe.com/docs/stripe-js/elements/payment-request-button

No "resize" button, rather a hover icon

**Comment by dgarcia360** [comment]
@tzach I've updated the PR with a new proposal. You can test it pulling the latest commit.

If it does not work as expected, please remove the cache or open the documentation site in incognito mode.

**Comment by tzach** [comment]
LGTM

**Pull request merged**
