### PR TITLE
Change sidebar color to gray

### PR DESCRIPTION
**Pull request by dgarcia360**
## Context

> Left sidebar color is too strong

This PR adds a background gradient to the sidebar.

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:

```
make preview
````

3. Open http://127.0.0.1:5500/ with your favorite browser, and enter an internal page. The sidebar should look as follows:

image

With scrollbar:

image

With multiversion:

image

### CODE REVIEW

**Comment by tzach** [comment]
Thanks @dgarcia360 the gradient is a little bit too much, in particular since we already have a gradient at the top
Can we try a slightly lighter shade instead?

https://youtu.be/Mb3iPP-tHdA

**Comment by dgarcia360** [comment]
Here's a second option with white background:

image


What do you think? It does not look bad at all, but I still prefer the current design (with the blue sidebar).

**Comment by dgarcia360** [comment]
Here's a third option (gray sidebar), using the same color schema as the search box:

image

**Comment by dgarcia360** [comment]
Here's a fourth option, using the original blue color but with a 50% transparency:

image

**Comment by tzach** [comment]
Gray is the best!

**Comment by dgarcia360** [comment]
Here's fifth option to consider:

Not change the color of the sidebar, but the color of the searchbox and code blocks from gray to blue:

image
I prefer this option, since we are using this same blue as well in the home page hero box:

image

**Comment by dgarcia360** [comment]
@tzach Updated the PR, now the sidebar is gray:

image

I've also updated the tables design to match the new color palette.

**Before:**

image

**Now:**

image

Note that change is opinionated. For example, I prefer how the blue color looks like in the sidebar since is less inconspicuous than the gray. It might be best to gather other's opinions before merging this change.

**Comment by tzach** [comment]
For some reason, the top menu in the PR is not visible, and the banner can not be closed

### Old
image

### New
image

**Comment by tzach** [comment]
Might be a cache refresh issue

**Comment by tzach** [comment]
Agree. Lets stay with the current blue.
Closing

**Pull request closed without merging**
