### PR TITLE
Add collapsible sidebar

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/193

I moved the selector to the bottom and inside the sidebar to not have conflicts with the scrollbar or the multiversion selector.

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:

```
make preview
````

3. Open http://127.0.0.1:5500/ with your favorite browser, and enter an internal page.

The sidebar collapsed should look like:

image

The sidebar expanded should look like:

image

### CODE REVIEW

**Comment by tzach** [comment]
Two points to consider:
1. The Previous  and Collapse buttons look the same
image

2. The Button is not always visible, hidden behind the footer
image

**Comment by dgarcia360** [comment]
> The Previous and Collapse buttons look the same

We can try with another icon, for example:

image

I'll keep you posted once I update the PR.

> The Button is not always visible, hidden behind the footer

Good catch! Fixed with the latest commit, please run ``make clean`` before running again ``make preview``.

**Comment by dgarcia360** [comment]
@tzach Collapsible button updated with round borders and new icon.

Preview:

image

image

**Review by tzach — COMMENTED** [review]
LGTM

**Pull request merged**
