### PR TITLE
Add like / dislike button

### PR DESCRIPTION
**Pull request by dgarcia360**
Adds the like / dislike button at the bottom of the page.

### CODE REVIEW

**Comment by annastuchlik** [comment]
I think the wording should be:

`Was this page helpful?`

Like:
`Great! Thanks for your feedback.`

Dislike:
`Thanks for your feedback! If you have any suggestions on how we can improve, please don't hesitate to create an issue.`

@tzach Let me know if you have any comments.

**Comment by tzach** [comment]
Maybe

> Thanks for your feedback! 
> Please don't hesitate to create an issue if you have any suggestions on how we can improve.

**Comment by annastuchlik** [comment]
@dgarcia360 Let's use the wording above. I can't update this PR, so it would be great if you could do it when you can.

**Comment by annastuchlik** [comment]
I've run the preview, but it doesn't look as expected on my side.
The wording is unchanged, and the buttons are not there. 
image

I've run it on the clean checkout, but the results are the same.

**Review by annastuchlik — APPROVED** [review]
LGTM

**Pull request merged**
