### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by kwiato**

### CODE REVIEW

**Comment by dgarcia360** [comment]
Feedback:

-  [ ] Page with banner looks off:

    image

    You can preview it by setting the following in conf.py:
   
    ```
    html_theme_options = {
    (...)
    "hide_banner": "false",
    ```

-  [ ] Some pages in Mac 13" screen introduce now an horizontal scrollbar (e.g. **Getting started > Quickstart**):

    image

-  [ ] Left & right sidebar blinks when reaching the end of the page: https://www.awesomescreenshot.com/video/34852760?key=2e3e25b17ace471894f832094e1aea91

**Review by dgarcia360 — APPROVED** [review]

**Comment by dgarcia360** [comment]
LGTM!

I added some edits:

- Changed anchor icon & updated icons lib
- Anchor icon is copied on hover + click
- Add configurable brand variables in conf.py

**Comment by dgarcia360** [comment]
@annastuchlik ready for review

**Comment by tzach** [comment]
@kwiato @dgarcia360  in the future, please include before and after UI capture in the PR comments.
It would make review easier. Thanks

**Pull request merged**
