### PR TITLE
Highlight current project

### PR DESCRIPTION
**Pull request by dgarcia360**
This pull request:

1. Highlights the current project on the sidebar:

image

2. Adds "ScyllaDB Docs" in front of the breadcrumb list:

image

## How to test this PR

1. Clone this PR and go to the `docs` folder.
2. Run `make preview` or `make multiversionpreview`.
3. Open http://127.0.0.1:5500/
4. Check the sidebar and breadcrumbs.

### CODE REVIEW

**Comment by tzach** [comment]
I think its the right direction
Not sure about the look when there is no version box (below), but we can improve it later
image

**Comment by annastuchlik** [comment]
The breadcrumbs look great.

The project name now renders differently - it's not in bold. As a result, if there's no version drop-down, it looks as if it was part of the page tree:

image

Could you modify the project name to make it bold and bigger, or anything else that would clearly differentiate the project name from the page tree?

**Comment by dgarcia360** [comment]
@annastuchlik This seems to be related with cache. Could you please try [cleaning the browser cache](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop) or opening the site in a new incognito window?

**Comment by annastuchlik** [comment]
@dgarcia360 Sorry for the confusion. It looks good.

**Review by annastuchlik — APPROVED** [review]
LGTM

**Pull request merged**
